name: "Build"

on:
  pull_request:
  push:
    branches:
      - main

env:
  php-tools: "composer:v2"

jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP with pecl extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run PHPStan
        run: composer phpstan
